## 1.	Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age. 

In [16]:
Name = "Ragavarshini S"
Age = "20"  

print("Hi my name is", Name)
print("My age is", Age)

Hi my name is Ragavarshini S
My age is 20


## 2.	X="Datascience is used to extract meaningful insights." Split the string.

In [4]:
X = "Datascience is used to extract meaningful insights."
split_words = X.split()

print(split_words)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


## 3.	Make a function that gives multiplication of two numbers 

In [5]:
def multiply_numbers(a, b):
    result = a * b
    return result

In [6]:
n1 = 10
n2 = 20

multiplication_result = multiply_numbers(n1, n2)
print("The multiplication result is:", multiplication_result)

The multiplication result is: 200


## 4.	Create a Dictionary of 5 States with their capitals. also print the keys and values. 

In [7]:
countries_capitals = {
    "India": "New Delhi",
    "United States": "Washington, D.C.",
    "United Kingdom": "London",
    "Germany": "Berlin",
    "Japan": "Tokyo"
}

# Print the keys
print("Country Names:")
for country in countries_capitals:
    print(country)

# Print the values
print("\nCapital Cities:")
for capital in countries_capitals.values():
    print(capital)

# Print both keys and values
print("\nCountry-Capital Pairs:")
for country, capital in countries_capitals.items():
    print(country, "-", capital)


Country Names:
India
United States
United Kingdom
Germany
Japan

Capital Cities:
New Delhi
Washington, D.C.
London
Berlin
Tokyo

Country-Capital Pairs:
India - New Delhi
United States - Washington, D.C.
United Kingdom - London
Germany - Berlin
Japan - Tokyo


## 5.	Create an identity matrix of dimension 4 by 4 

In [8]:
def create_identity_matrix(n):
    matrix = [[0] * n for _ in range(n)]  # Initialize the matrix with zeros

    for i in range(n):
        matrix[i][i] = 1  # Set the diagonal elements to 1

    return matrix

# Create a 4x4 identity matrix
identity_matrix = create_identity_matrix(4)

# Print the matrix
for row in identity_matrix:
    print(row)


[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


## 7.	Create a 3x3 matrix with values ranging from 1 to 9 

In [10]:
def create_matrix():
    matrix = [[0] * 3 for _ in range(3)]  # Initialize a 3x3 matrix with zeros

    value = 1
    for i in range(3):
        for j in range(3):
            matrix[i][j] = value
            value += 1

    return matrix

# Create a 3x3 matrix with values ranging from 1 to 9
matrix = create_matrix()

# Print the matrix
for row in matrix:
    print(row)


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


## 8.	Create 2 similar dimensional array and perform sum on them. 

In [11]:
def sum_arrays(array1, array2):
    rows = len(array1)
    cols = len(array1[0])

    result = [[0] * cols for _ in range(rows)]

    for i in range(rows):
        for j in range(cols):
            result[i][j] = array1[i][j] + array2[i][j]

    return result

# Create two similar dimensional arrays
array1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

# Perform the sum operation
sum_result = sum_arrays(array1, array2)

# Print the result
for row in sum_result:
    print(row)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


## 9.	Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive) 

In [12]:
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

current_date = start_date
while current_date <= end_date:
    print(current_date.strftime("%Y-%m-%d"))
    current_date += timedelta(days=1)


2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


## 10.	Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]} 

In [13]:
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}

df = pd.DataFrame(dictionary)

print(df)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240


## 6. Create an identity matrix of dimension 4 by 4

In [14]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
